# Questions on numpy 


In [2]:
import numpy as np

## 1. You're given student test scores. Create a program that performs basic analysis:
python

student_scores = [
    [85, 92, 78, 96, 88],  # Student 1's scores across 5 tests
    [79, 85, 91, 87, 83],  # Student 2
    [92, 88, 95, 91, 89],  # Student 3
    [76, 82, 79, 85, 81],  # Student 4
    [88, 91, 87, 93, 90]   # Student 5
]

Tasks:
1. Convert to NumPy array and explore its properties
2. Calculate each student's average score using array operations
3. Find the highest and lowest score in the entire dataset
4. Identify which test (column) had the highest average score
5. Create a boolean array showing scores above 90
6. Use slicing to get the first 3 students' scores on the last 2 tests

### Task 1

In [76]:
student_scores = np.array ([
    [85, 92, 78, 96, 88],  # Student 1's scores across 5 tests
    [79, 85, 91, 87, 83],  # Student 2
     [92, 88, 95, 91, 89], # Student 3
    [76, 82, 79, 85, 81],  # Student 4
    [88, 91, 87, 93, 90]   # Student 5
])

In [77]:
student_scores

array([[85, 92, 78, 96, 88],
       [79, 85, 91, 87, 83],
       [92, 88, 95, 91, 89],
       [76, 82, 79, 85, 81],
       [88, 91, 87, 93, 90]])

In [78]:
student_scores.dtype

dtype('int64')

In [79]:
student_scores.ndim

2

In [80]:
student_scores.shape

(5, 5)

In [81]:
student_scores.size

25

### Task 2

In [82]:
s1 = np.array ([85, 92, 78, 96, 88]) #Student 1's scores
s2 = np.array ([79, 85, 91, 87, 83]) #Student 2's scores
s3 = np.array ([92, 88, 95, 91, 89]) #Student 3's scores
s4 = np.array ([76, 82, 79, 85, 81]) #Student 4's scores
s5 = np.array ([88, 91, 87, 93, 90]) #Student 5's scores

In [83]:
s1.mean()

np.float64(87.8)

In [84]:
s2.mean()

np.float64(85.0)

In [85]:
s3.mean()

np.float64(91.0)

In [86]:
s4.mean()

np.float64(80.6)

In [87]:
s5.mean()

np.float64(89.8)

### Task 3

In [88]:
student_scores

array([[85, 92, 78, 96, 88],
       [79, 85, 91, 87, 83],
       [92, 88, 95, 91, 89],
       [76, 82, 79, 85, 81],
       [88, 91, 87, 93, 90]])

In [89]:
student_scores.max()

np.int64(96)

In [90]:
student_scores.min()

np.int64(76)

### Task 4

In [91]:
student_scores.argmax()

np.int64(3)

### Task 5

In [92]:
student_scores>=90

array([[False,  True, False,  True, False],
       [False, False,  True, False, False],
       [ True, False,  True,  True, False],
       [False, False, False, False, False],
       [False,  True, False,  True,  True]])

In [93]:
student_scores[student_scores>=90]

array([92, 96, 91, 92, 95, 91, 91, 93, 90])

### Task 6

In [94]:
student_scores[:3, -2:]

array([[96, 88],
       [87, 83],
       [91, 89]])

## 2. Analyze student performance across multiple subjects:
np.random.seed(456)
num_students, num_subjects = 50, 6
subject_names = ['Math', 'Science', 'English', 'History', 'Art', 'PE']
scores = np.random.randint(60, 100, (num_students, num_subjects))

Tasks:
1. Find students who excel in STEM (Math + Science average > 90)
2. Identify struggling students (any subject < 70) and which subjects they struggle with
3. Find the most challenging subject (lowest average) and best performers in that subject


In [95]:
np.random.seed(456)

In [96]:
subject_names = ['Math', 'Science', 'English', 'History', 'Art', 'PE']

In [97]:
scores = np.random.randint(60, 100, (50, 6))

In [98]:
scores

array([[87, 97, 85, 88, 75, 97],
       [88, 99, 77, 71, 73, 65],
       [94, 74, 80, 94, 62, 64],
       [68, 81, 98, 76, 70, 68],
       [95, 95, 82, 95, 82, 70],
       [81, 77, 66, 91, 71, 81],
       [86, 85, 72, 80, 62, 64],
       [75, 65, 64, 81, 91, 93],
       [70, 87, 85, 64, 71, 90],
       [88, 65, 67, 83, 72, 85],
       [75, 80, 77, 86, 92, 74],
       [72, 68, 95, 68, 75, 87],
       [75, 90, 76, 99, 70, 93],
       [96, 67, 79, 97, 85, 74],
       [80, 94, 73, 71, 86, 86],
       [84, 89, 64, 99, 88, 69],
       [82, 60, 86, 60, 71, 71],
       [84, 73, 73, 97, 98, 82],
       [63, 75, 89, 98, 81, 76],
       [98, 75, 71, 81, 83, 78],
       [62, 93, 70, 85, 62, 96],
       [76, 62, 66, 79, 73, 77],
       [98, 77, 60, 86, 87, 67],
       [92, 73, 69, 72, 74, 69],
       [75, 91, 71, 94, 65, 91],
       [64, 80, 85, 65, 73, 64],
       [83, 92, 66, 79, 69, 65],
       [89, 99, 89, 88, 73, 66],
       [69, 72, 89, 71, 68, 80],
       [78, 91, 71, 90, 84, 84],
       [96

### Task 1

In [99]:
scores [scores[:, 0] > 90, 0] #students who excel in math

array([94, 95, 96, 98, 98, 92, 96, 91, 99, 94, 91, 91], dtype=int32)

In [100]:
scores [scores[:, 1] > 90, 1] #students who excel in science

array([97, 99, 95, 94, 93, 91, 92, 99, 91, 98, 99], dtype=int32)

In [101]:
((scores[:, 0] +  scores[:, 1]) / 2)[((scores[:, 0] + scores[:, 1]) / 2) > 90] #students who excel in stem

array([92. , 93.5, 95. , 94. , 94.5])

### Task 2

In [102]:
np.any(scores < 70, axis = 1) #struggling students boolean values

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True, False,  True,  True, False,  True,
        True,  True,  True, False,  True])

In [103]:
np.where(np.any(scores < 70, axis = 1)) #struggling students

(array([ 1,  2,  3,  5,  6,  7,  8,  9, 11, 13, 15, 16, 18, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 30, 31, 32, 34, 35, 36, 38, 39, 41, 42, 44, 45,
        46, 47, 49]),)

In [133]:
scores < 70 #subjects they struggle with are marked 'True' in the array

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False,  True,  True],
       [ True, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False,  True,  True],
       [False,  True,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False,  True, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False,  True, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, Fa

### Task 3

In [105]:
subject_names[np.argmin(scores.mean(axis=0))] #most challenging subject name

'Art'

In [106]:
scores [:, np.argmin(scores.mean(axis=0))].max() #highest score in the most challenging subject

np.int32(99)

In [107]:
np.where(
    scores[:, np.argmin(scores.mean(axis=0))] 
    == scores[:, np.argmin(scores.mean(axis=0))].max()
) [0] + 1                                               #best performers in the most challenging subject

array([41, 43])

## 3. Analyze a stock portfolio using NumPy's mathematical functions:
np.random.seed(789)
days = 252  # Trading days in a year
stocks = 5

Simulate daily returns (percentage changes)
daily_returns = np.random.normal(0.001, 0.02, (days, stocks))  # Mean 0.1% daily return, 2% volatility
stock_names = ['AAPL', 'GOOGL', 'MSFT', 'TSLA', 'AMZN']
initial_prices = np.array([150, 2800, 300, 800, 3200])

Tasks :
1. Basic Analysis
 -Calculate cumulative returns for each stock
 -Find annualized volatility (standard deviation * sqrt(252))
 -Identify best and worst performing stocks
2. Risk Metrics
 -Calculate Sharpe ratio (return/volatility) for each stock
 -Find maximum drawdown (largest peak-to-trough decline)
 -Calculate correlation matrix between stocks

In [113]:
np.random.seed(789)

In [114]:
days = 252  # Trading days in a year
stocks = 5

In [115]:
#Simulate daily returns (percentage changes)
daily_returns = np.random.normal(0.001, 0.02, (days, stocks))  # Mean 0.1% daily return, 2% volatility
stock_names = ['AAPL', 'GOOGL', 'MSFT', 'TSLA', 'AMZN']
initial_prices = np.array([150, 2800, 300, 800, 3200])

In [116]:
daily_returns

array([[-0.02116223, -0.01351437,  0.01145609,  0.02568884,  0.00293792],
       [-0.01875844,  0.00234466, -0.01085184, -0.01763542,  0.02210726],
       [ 0.01710345,  0.02771369, -0.00750256, -0.00537071, -0.01628741],
       ...,
       [-0.00594361, -0.00918097,  0.0290994 , -0.02367441, -0.01087742],
       [-0.0119153 , -0.01296554, -0.00542998,  0.01199449,  0.00495045],
       [ 0.00849359,  0.02542862,  0.00152298,  0.00522356,  0.01760987]],
      shape=(252, 5))

### Task 1

In [118]:
# Basic analysis
## Calculate cumulative returns for each stock
cumulative_returns = np.prod(1 + daily_returns, axis=0) - 1

In [120]:
cumulative_returns

array([ 0.01870374,  0.38287184, -0.07640889,  1.57901117,  0.17106723])

In [111]:
# Find annualized volatility (standard deviation * sqrt(252))
daily_std = np.std(daily_returns, axis=0)

In [112]:
annualized_volatility = daily_std * np.sqrt(252)

In [121]:
annualized_volatility

array([0.31831822, 0.34095784, 0.30405824, 0.32419373, 0.2983928 ])

In [122]:
# Best and worst performing stocks
best = np.argmax(cumulative_returns)
worst = np.argmin(cumulative_returns)

In [123]:
best

np.int64(3)

In [124]:
worst

np.int64(2)

### Task 2

In [126]:
# Risk Metrics 
# Calculate Sharpe ratio (return/volatility) for each stock 
sharpe_ratio = cumulative_returns / annualized_volatility

In [127]:
sharpe_ratio

array([ 0.058758  ,  1.12293014, -0.25129688,  4.87057896,  0.57329543])

In [129]:
# Find maximum drawdown (largest peak-to-trough decline) 
prices = initial_prices * np.cumprod(1 + daily_returns, axis=0) #prices over time
peak = np.maximum.accumulate(prices, axis=0) #running peak
drawdown = (prices - peak) / peak #drawdown
max_drawdown = np.min(drawdown, axis=0) #maximum drawdown

In [130]:
max_drawdown

array([-0.22714481, -0.28661051, -0.43894286, -0.11172979, -0.21783847])

In [131]:
# Calculate correlation matrix between stocks
correlation_matrix = np.corrcoef(daily_returns, rowvar = False)

In [134]:
correlation_matrix

array([[ 1.        ,  0.01558858,  0.0016994 , -0.10262945,  0.08717904],
       [ 0.01558858,  1.        , -0.15014226,  0.08813674,  0.03835865],
       [ 0.0016994 , -0.15014226,  1.        ,  0.01366414, -0.02847043],
       [-0.10262945,  0.08813674,  0.01366414,  1.        , -0.11192288],
       [ 0.08717904,  0.03835865, -0.02847043, -0.11192288,  1.        ]])